---
title: Bernardo Lanza - Developer | Ph.D. student
layout: default
description: Bernardo Lanza's portfolio - Developer and Ph.D. student specializing in deep learning and machine vision for agriculture. " - Free software is a matter of liberty, not price. To understand the concept, you should think of 'free' as in 'free speech,' not as in 'free beer.'"
keywords: Bernardo Lanza, developer, Ph.D. student, deep learning, machine vision, agriculture, mechatronics, AI, robotics
theme: jekyll-theme-minimal
---