---
title: Bernardo Lanza Developer | Ph.D. in Mechatronics | Robotics and Sensing Engineer
layout: default
description: "Bernardo Lanza's portfolio - Developer and Ph.D. in Mechatronics. Robotics and sensing engineer specialized in agricultural perception and field-deployable vision systems."
keywords: Bernardo Lanza, developer, Ph.D. in mechatronics, robotics, sensing engineer, agricultural perception, field-deployable vision systems, deep learning, machine vision, AI
theme: jekyll-theme-minimal
url: "https://bernardolanza93.github.io"
baseurl: "/portfolio"
sitemap: "sitemap.xml"
---
